<template>
  <div>
    <div class="">
        Somos Huella Hi
    </div>
    <div class="">
    </div>
    
  </div>
</template>

<style lang="scss" scoped>
  h2 {
    color: #00B4CE;
    margin-top: 20px;
  }
  p {
    color: #9B9B9B;
    margin-top: 10px;
  }
  .card-info {
    margin-top: 80px;
  }
  .title {
    color: #21BFD5;
    margin-top: 30px;
  }
    h1 {
      margin: 20px;
    }
</style>
